name: Production Deployment

on:
  release:
    types: [published]

jobs:
  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.PRODUCTION_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build Application
        run: npm run build:ci
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Vercel
        run: >
          vercel
          --token ${{ secrets.VERCEL_PRODUCTION_TOKEN }}
          --prod
          --yes
          --scope ${{ secrets.VERCEL_ORG_ID }}
